#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:30:00
#PBS -N app-freesurfer-longitudinal-stats
#PBS -V

set -x
set -e

subjectID=`jq -r '._inputs[0].meta.subject' config.json`
fsaverage=`jq -r '.fsaverage' config.json`

# copy over fsaverage data
[ ! -d ./${fsaverage} ] && cp -R ${SUBJECTS_DIR}/${fsaverage} ./${fsaverage} && chmod -R +w ./${fsaverage}

# copy license and export path for freesurfer
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" #&& #exit 1;
echo $FREESURFER_LICENSE > license.txt

# convert surfaces and generate appropriate summary statistic text files
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.1.1 ./compute-long-stats.sh

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.5.0 ./convert-to-cortexmap.sh

# generate csv's for each statistic that can be useful in MLC analyses
time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./createParcellationCSVs.py

if [ -f ./parc-stats/parc-stats/longitudinal_stats_aparc.DKTatlas.csv ]; then
	rm -rf ./tmpstats fsaverage* *${subjectID}* qdec
	echo "complete"
	exit 0
else
	echo "stats computations failed somewhere. please check logs and derivatives"
	exit 1
fi
